---
# application tasks to be customized and to run after the main provision

# - name: Install git
#  apt: name=git state=latest

- name: Clone Collective Access
  git: >
   repo=https://github.com/collectiveaccess/providence
   dest=/opt/vic-ca
   update=no
   version=release-1.5

- name: Configure setup.php
  sudo: yes
  template: src=setup.tpl dest=/opt/vic-ca/setup.php

- name: Set permissions on app/tmp
  file: path=/opt/vic-ca/app/tmp state=directory owner=www-data group=www-data mode=775

- name: Set permissions on vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache
  file: >
   path=/opt/vic-ca/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache
   state=directory
   owner=www-data
   group=www-data
   mode=775

- name: Set permissions on /opt/vic-ca/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer
  file: >
   path=/opt/vic-ca/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer
   state=directory
   owner=www-data
   group=www-data
   mode=775

- name: Set permissions on media
  file: path=/opt/vic-ca/media state=directory owner=www-data group=www-data mode=755
# - name: Set permissions on app/tmp
#   command: chmod +w /opt/vic-ca/app/tmp
#
# - name: Set permissions on vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache
#   command: chmod +w /opt/vic-ca/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache
